### ISSUE TITLE
Add timezone to pagerduty user resource

### ISSUE THREAD

**Issue by catkins** [faros-ai/airbyte-connectors#1087]
Hi there 👋

We've just started using your super handy Pagerduty connector. I notice that the users record is just the name and email (and a few other standard fields) for the moment.

https://github.com/faros-ai/airbyte-connectors/blob/main/sources/pagerduty-source/src/pagerduty.ts#L60-L63

I'd love to add the time_zone attribute if possible? The role and contact methods attributes would be great too if its not too much trouble?

https://developer.pagerduty.com/api-reference/b3A6Mjc0ODIzMw-list-users

How do enhancements usually get added to the connectors that Faros manage? I can open a PR if its not a priority.

**Comment by tovbinm** [comment]
Thank you! Please open a PR and we will review.
