### ISSUE TITLE
Add Bitbucket connector

### ISSUE THREAD

**Issue by yevgenius** [faros-ai/airbyte-connectors#165]
Please see if this draft is useful to work off of https://github.com/faros-ai/airbyte-connectors/pull/122

**Comment by Roma-Kyrnis** [comment]
Hi @yevgenius @tovbinm I cannot find the right way authorize to bitbucket. Can you help me?

I found **local** [API docs](https://bitbucketjs.netlify.app/) but token or username/password doesn't work, I got 404 or 401 errors.
Also, I found **bitbucket** [API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/) but I cannot find which token or username/password use

**Comment by tovbinm** [comment]
You create an application password here -
https://bitbucket.org/account/settings/app-passwords/
And use your email + app password to authenticate.

-Matthew
