### ISSUE TITLE
Bitbucket connector does not link issues to a tms_Project or tms_TaskBoard

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/airbyte-connectors#341]
A good default is to do the same as our GitHub connector: create a project and a board for each repository. Tasks (issues) should then link to those.
https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/src/converters/github/common.ts#L92

**Comment by huongtn** [comment]
@tovbinm I added to same branch as #339, because update same model( repository)
https://github.com/faros-ai/airbyte-connectors/pull/343

**Comment by huongtn** [comment]
https://github.com/faros-ai/airbyte-connectors/pull/348
