### ISSUE TITLE
GitLab connector does not link issues to a tms_Project or tms_TaskBoard

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/airbyte-connectors#342]
A good default is to do the same as our GitHub connector: create a project and a board for each repository. Tasks (issues) should then link to those.
https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/src/converters/github/common.ts#L92

**Comment by tovbinm** [comment]
yep. and it was already supported in the original feed - https://github.com/faros-ai/feeds/blob/master/feeds/vcs/gitlab-feed/src/feed.ts
