### ISSUE TITLE
Add OpsGenie Connector and Converters

### ISSUE THREAD

**Issue by willmarks** [faros-ai/airbyte-connectors#364]
We would like to build a connecter and converters for OpsGenie. To start, this should be a similar connector to that of PagerDuty as we are interested in incident data.

Data to retrieve:
- Incidents
- Users

[API Docs](https://docs.opsgenie.com/docs)

Note: Be aware of [rate-limiting](https://docs.opsgenie.com/docs/api-rate-limiting) when using [node.js API client](https://docs.opsgenie.com/docs/opsgenie-nodejs-api#nodejs-sdk-installation) as it does not appear to handle 429 responses

**Comment by huongtn** [comment]
@willmarks because [node.js API client](https://docs.opsgenie.com/docs/opsgenie-nodejs-api#nodejs-sdk-installation) does not support incident query, so I just use axios.
