### ISSUE TITLE
Add BambooHR connector and converters

### ISSUE THREAD

**Issue by sasher** [faros-ai/airbyte-connectors#435]

**Comment by huongtn** [comment]
@sasher what source and destination data do I need to pull?

**Comment by tovbinm** [comment]
Employee & team information to fit into Faros `org` and `identity` schemas.

**Comment by huongtn** [comment]
@tovbinm As I explored BamBooHR not support team information, please advice?

**Comment by tovbinm** [comment]
So far, what are we able to fetch?

**Comment by huongtn** [comment]
We can get employee, manager, location, department
