### ISSUE TITLE
Wrap Faros GitHub feed as Airbyte Source

### ISSUE THREAD

**Issue by thomas-gerber** [faros-ai/airbyte-connectors#489]
Develop a universal Airbyte source to run Faros feeds starting with GitHub feed.

What's needed?
 
* `feeds-sdk` to be able to output raw records to stdout
* feed config can be generic (params) and passed into the feed as args
* special "identity" converter in the Faros destination

Questions:
* what about dates representation between AirbyteRecord and JSON
* how do we package it? one container per Faros feed? or all Faros feeds packaged in a single container?

**Comment by tovbinm** [comment]
Done.
