### ISSUE TITLE
Jira converter should handle "To Do" status category name

### ISSUE THREAD

**Issue by ypc-faros** [faros-ai/airbyte-connectors#490]
Caught by:

https://github.com/faros-ai/airbyte-connectors-tests/runs/6711842920?check_suite_focus=true#step:5:134

Inputs: https://github.com/faros-ai/airbyte-connectors-tests/blob/main/sources/jira/all-streams.log

**Comment by tovbinm** [comment]
It would be nice to have these tickets open automatically ;)

**Comment by ogusak** [comment]
https://faros-ai.atlassian.net/browse/FAI-1911

**Comment by tovbinm** [comment]
Fixed - https://github.com/faros-ai/airbyte-connectors/blob/main/destinations/airbyte-faros-destination/src/converters/jira/issues.ts#L38
