### ISSUE TITLE
Circular dependencies wrongly detected

### ISSUE THREAD

**Issue by szubster** [faros-ai/airbyte-connectors#589]
Code for detecting circular dependencies does not work correctly. It detects all chains, not only circular dependencies.

https://github.com/faros-ai/airbyte-connectors/blob/51a9b4a8fbe31e6760e1604885e26103d1394254/destinations/airbyte-faros-destination/src/destination.ts#L650

Example:
Stream A
Stream B depending on Stream A
Stream C depending on Stream B

Error message:
```
{"log":{"level":"INFO","message":"Records of stream C will be accumulated and processed last, since their converter has dependencies on streams: B"},"type":"LOG"}
Debugger ending on ws://127.0.0.1:9229/5070f89e-47ca-4e6f-9930-40e7e60b02bb
For help, see: https://nodejs.org/en/docs/inspector
{"log":{"level":"ERROR","message":"Encountered an error while writing to destination: VError: Circular converter dependency detected: B - {\"jse_shortmsg\":\"Circular converter dependency detected: B\",\"jse_info\":{},\"message\":\"Circular converter dependency detected: B\"}"},"type":"LOG"}
```

**Comment by tovbinm** [comment]
Thanks @cjwooo 

@szubster released in v0.2.20
