### ISSUE TITLE
Calling StreamContext.getAll() in onProcessingComplete returns nothing

### ISSUE THREAD

**Issue by szubster** [faros-ai/airbyte-connectors#604]
After updating `airbyte-faros-destination` from `0.1.88` to `0.2.22` a call to `ctx.getAll()` inside overriden `onProcessingComplete(streamName)` in our own converter shows nothing.
streamName is passed as dependency of the converter.
Even more, the `recordsByStreamName` property of `StreamContext` is just an empty object.

**Comment by szubster** [comment]
Same behavior on 0.2.24

**Comment by tovbinm** [comment]
@cjwooo can we close this now?

**Comment by tovbinm** [comment]
The fix was released in https://github.com/faros-ai/airbyte-connectors/releases/tag/v0.2.25
