### ISSUE TITLE
Connector in its own isolated project

### ISSUE THREAD

**Issue by chrispytoes** [faros-ai/airbyte-connectors#664]
Why do the docs say you need to download this entire repo and install ALL dependencies for ALL sources just to develop a new connector? Is it possible to keep things slim and simple by just building a connector in its own repo?

I'm looking to write a JS connector but I want to know how much bloat I can remove from the project.

**Comment by cjwooo** [comment]
You can setup your own project with [faros-airbyte-cdk](https://www.npmjs.com/package/faros-airbyte-cdk) as a dependency.

**Comment by tovbinm** [comment]
Additionally you can pretty much follow [this guide](https://github.com/faros-ai/airbyte-connectors/blob/main/sources/README.md) or just look on how one of our sources/destinations are build.

**Comment by tovbinm** [comment]
Generally we like the idea to have a repo per source/destination but it makes development flow quite slow, so we keep them together.
