### ISSUE TITLE
Airbyte PagerDuty connector - Source cannot be stopped!

### ISSUE THREAD

**Issue by alexismanuel** [faros-ai/airbyte-connectors#733]
Hi, I did not find any issues related to my problem so here it is. My setup:
- Airbyte version 0.40.6
- PagerDuty source connector version 0.1.23
- Postgres destination connector version 0.3.26

When running a simple sync of the `incidents` stream, the sync can not finish properly and returns every time a `Failure Origin: source, Message: Something went wrong within the source connector` error.

Here are logs related to one of the failed runs:
[logs-1086.txt](https://github.com/faros-ai/airbyte-connectors/files/9817584/logs-1086.txt)

**Comment by tovbinm** [comment]
It looks like you are running a PagerDuty source with Postgres destination and the source is failing after 10000 records due to invalid type of the incident entry:
```
2022-10-19 06:44:22 [44msource[0m > Encountered an error while reading stream PagerdutySource: 400: Bad Request
2022-10-19 06:44:22 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$6):363 - Total records read: 10000 (24 MB)
2022-10-19 06:44:22 [33mWARN[m i.a.w.g.DefaultReplicationWorker(lambda$getReplicationRunnable$5):366 - Schema validation errors found for stream incidents. Error messages: [$.incident_key is of an incorrect type. Expected it to be string, $.priority is of an incorrect type. Expected it to be object]
```

**Comment by tovbinm** [comment]
Can you try decreasing the `Cutoff Days` parameter on the source to 7-15 days and rerun?

**Comment by alexismanuel** [comment]
Thank you for your response, when I try to decrease the Cutoff Days value, it is recognized as a string instead of a number so it throws an error. Is there something I am doing wrong ?
<img width="714" alt="image" src="https://user-images.githubusercontent.com/22666624/196871562-3fa59063-71d3-4579-a5d6-e231b057e6b0.png">

**Comment by alexismanuel** [comment]
If I delete it then recreate it, I have the following error: 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/22666624/196872354-0e34e0a4-bb2b-408a-a756-71897221c125.png">

**Comment by tovbinm** [comment]
Can you try upgrading PagerDuty source to [0.4.6](https://github.com/faros-ai/airbyte-connectors/releases/tag/v0.4.6)?

**Comment by alexismanuel** [comment]
Airbyte does not provide it, is it a way for me to manually set the source version ? https://docs.airbyte.com/integrations/sources/pagerduty/

**Comment by tovbinm** [comment]
You can open Airbyte UI then navigate to Destinations and update the version there

**Comment by alexismanuel** [comment]
As you can see below, the Airbyte UI provides only as far as the 0.1.23 source connector (its is flagged as latest): 
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/22666624/197133898-f013633c-fa11-45c3-a0b7-fd45994bab9c.png">

**Comment by alexismanuel** [comment]
It worked this way, thank you !
