### ISSUE TITLE
Datadog has multiple regions this connector has no way of selecting the correct one.

### ISSUE THREAD

**Issue by nthbooth** [faros-ai/airbyte-connectors#856]
Datadog has multiple hosted regions: 
US1 - app.datadoghq.com
US3 - https://us3.datadoghq.com/
US5 - https://us5.datadoghq.com/
EU1 - https://app.datadoghq.eu/
US1-FED - https://app.ddog-gov.com/

there is no way behind the scenes to go between regions and you have to select the right region to get your data. 

It would be useful for the connector to have a URL box so that the user can enter the correct region for their connection (as I am sure that Datadog will add more regions in the future!

As it is hitting the US instance when valid APP and API keys are entered I get the following error (as I am on the EU instance)
The connection tests failed.
HTTP-Code: 403 Message: {"errors":["Forbidden"]}

Looking at the source it looks like you are using the following client: https://www.npmjs.com/package/@datadog/datadog-api-client 

This can accept different server regions:
Changing Server
When talking to a different server, like the eu instance, change the server variables:
```

import { client } from '@datadog/datadog-api-client';

const configuration = client.createConfiguration();

client.setServerVariables(configuration, {
  site: "datadoghq.eu"
});

```
Nick

**Comment by tovbinm** [comment]
Released in https://github.com/faros-ai/airbyte-connectors/releases/tag/v0.4.47
