### ISSUE TITLE
[Jenkins Source] Github OAuth

### ISSUE THREAD

**Issue by konfortes** [faros-ai/airbyte-connectors#870]
Hey guys,
We use Github oauth in Jenkins, therefore, configuring a source with user and API token is not possible for me.
Also - Jenkins jobs and builds can be accessed by non-authenticated users.
Any idea what can I do to use this source?

**Comment by tovbinm** [comment]
Are you suggesting that making API key authentication requirement optional would work for you?

**Comment by konfortes** [comment]
Hey @tovbinm 
Yep, it will definitely solve my issue

**Comment by konfortes** [comment]
@tovbinm I created this PR, lmk wdyt:
[https://github.com/faros-ai/airbyte-connectors/pull/871](https://github.com/faros-ai/airbyte-connectors/pull/871)

**Comment by tovbinm** [comment]
Released in https://github.com/faros-ai/airbyte-connectors/releases/tag/v0.4.52

**Comment by tovbinm** [comment]
Thank you for the contribution @konfortes
