### ISSUE TITLE
Request to add Notion as a connector

### ISSUE THREAD

**Issue by a-c-m** [faros-ai/airbyte-connectors#912]
https://developers.notion.com/
https://developers.notion.com/reference/retrieve-a-database

Specifically the ability to pull database entries as TMS - it may need more config, due to the highly flexible nature of Notion, as well as deeper multi database linkage (e.g. we use different databases for tickets and epics, with links between them).

**Comment by tovbinm** [comment]
This is quite a unique usecase. How would source identify the entires to fetch, e.g by tag, author, location?

**Comment by eskrm** [comment]
@a-c-m I've pushed a [PR](https://github.com/faros-ai/airbyte-connectors/pull/916) that adds converters for the community Notion [source](https://docs.airbyte.com/integrations/sources/notion/). Please take a look and provide any feedback there. I'll have someone from my team review it as well.

If you want to test it from the PR branch you can [build](https://github.com/faros-ai/airbyte-connectors#build-docker-images) the destination docker image and run it with the [airbyte-local-cli](https://github.com/faros-ai/airbyte-local-cli):

```
./airbyte-local.sh \
  --src airbyte/source-notion \
  --src-catalog-overrides '{"users": {"sync_mode": "full_refresh", "destination_sync_mode": "overwrite"}, "pages": {"sync_mode": "incremental", "destination_sync_mode": "append"}, "databases": {"disabled": true}, "blocks": {"disabled": true}}' \
  --src.credentials.auth_type token \
  --src.credentials.token $NOTION_TOKEN \
  --src.start_date 2023-01-01:00:00.000Z \
  --dst airbyte-faros-destination \
  --no-dst-pull \
  --dst.edition_configs.edition cloud \
  --dst.edition_configs.api_url https://prod.api.faros.ai \
  --dst.edition_configs.api_key $FAROS_API_KEY \
  --dst.edition_configs.graph default \
  --dst.source_specific_configs.notion.kind_property Kind \
  --dst.source_specific_configs.notion.projects.kind Project \
  --dst.source_specific_configs.notion.epics.kind Epic \
  --dst.source_specific_configs.notion.sprints.kind Sprint \
  --dst.source_specific_configs.notion.tasks.kind Task \
  --dst-stream-prefix mysource__notion__ \
  --connection-name mysource
```

This is just example config. You'll likely need to configure the `dst.source_specific_configs.notion` options further to match your Notion setup. The PR has all the options along with descriptions, but let me know if you have questions.

**Comment by eskrm** [comment]
@a-c-m You can use our latest published image for `farosai/airbyte-faros-destination` or anything starting from 0.4.70. No need to build the image from the branch anymore.
